# -*- coding: utf-8 -*-
"""pattern_essence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUQtDtxdu_axMVAm9jLH71n2UeWG1jjz

Understanding the behaviour of python's print function
"""

print("Hello", end="")
print("World")

print("Hello", end=" ")
print("World")

print("Hello")
print()      # same as new line '\n'
print("World")

"""Visualizing the matrix grid of two nested for loops for better context and understanding"""

for row in range(0, 10):
  for col in range(0,10):
    print([row, col], end="")
  print()

"""Developing logic based on the matrix rows, columns observation"""

for row in range(0, 5):
  for col in range(0,5):
    if row+col < 4:
      print(" ", end="")
    else:
      print(".", end="")
  print()

def pattern(n):
  for row in range(0, n):
    for col in range(0,n):
      if row+col < n-1:
        print(" ", end=" ")
      else:
        print(".", end=" ")
    print()
pattern(10)

def pattern(n):
  for row in range(0, n):
    for col in range(0,n):
      if row+col > n-1:
        print(" ", end=" ")
      else:
        print(".", end=" ")
    print()
pattern(10)

def pattern(n):
  for row in range(0, n):
    for col in range(0,n):
      if row>col:
        print(".", end=" ")
    print()
pattern(10)

def pattern(n):
  for row in range(0, n):
    for col in range(0,n):
      if row<col:
        print(".", end=" ")
    print()
pattern(10)

def pattern(n):
  for row in range(0, n):
    for col in range(0,n):
      if row+col < n-1:
        print(" ", end="")
      else:
        print(".", end=" ")
    print()
pattern(10)

def pattern(n):
  for row in range(0, n):
    for col in range(0,n):
      if col < row:
        print(" ", end="")
      else:
        print(".", end=" ")
    print()
pattern(10)

def pattern(n):
  for row in range(0, n):
    for col in range(0,n):
      if row+col < n-1:
        print(" ", end="")
      else:
        print(".", end=" ")
    print()
  for row in range(1, n):    # Start from row 1 to skip the extra print
    for col in range(0, n):
      if col < row:
        print(" ", end="")
      else:
        print(".", end=" ")
    print()
pattern(10)

